version: '3.8'

services:
  app:
    build: .
    container_name: nest_poc
    env_file:
      - .env
    ports:
      - '${PORT}:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
